/************TEST DRIVER FOR TEST CASE TC_1 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../binarysearch.c"
#include "../../../pathcrawler_binarysearch/lanceur_binarySearch_params.h"
#undef main


int main()
{
//declarations
//allocations
arr = NULL;
//assignments
size = 0;
target = 0;
//function call
binarySearch(arr, size, target);
//disallocation
//end
}
