/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

int binarySearch(int *arr, int size, int target)
{
  int __retres;
  int low = 0;
  int high = size - 1;
  while (1) {
    if (low <= high) {
      pathcrawler_trace_full("+134","l.3, file binarysearch.c");
      goto lin_while_body_2;
    }
    else {
      pathcrawler_trace_full("-134","l.3, file binarysearch.c");
      goto lin_while_break_1;
    }
    lin_while_body_2:
    {
      int mid = low + (high - low) / 2;
      if (*(arr + mid) == target) {
        pathcrawler_trace_full("+140","l.5, file binarysearch.c");
        lin_ite_body_6: {
                          __retres = mid;
                          goto return_label;
                        }
      }
      else {
        pathcrawler_trace_full("-140","l.5, file binarysearch.c");
        lin_ite_body_7: ;
      }
      if (*(arr + mid) < target) {
        pathcrawler_trace_full("+148","l.7, file binarysearch.c");
        lin_ite_body_11: low = mid + 1;
      }
      else {
        pathcrawler_trace_full("-148","l.7, file binarysearch.c");
        lin_ite_body_12: high = mid - 1;
      }
    }
  }
  lin_while_break_1: ;
  __retres = -1;
  return_label: return __retres;
}


