/************TEST DRIVER FOR TEST CASE TC_1 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../queue.c"
#include "../../../pathcrawler_queue/lanceur_enqueue_params.h"
#undef main


int main()
{
//declarations
//allocations
q = NULL;
//assignments
value = 0;
//function call
enqueue(q, value);
//disallocation
//end
}
