/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

void toLowerCase(char *str)
{
  int i = 0;
  while (1) {
    if ((int)*(str + i) != '\000') {
      pathcrawler_trace_full("+109","l.3, file lower.c");
      goto lin_for_body_2;
    }
    else {
      pathcrawler_trace_full("-109","l.3, file lower.c");
      goto lin_for_break_1;
    }
    lin_for_body_2:
    if ((int)*(str + i) >= 'A') {
      pathcrawler_trace_full("+114","l.4, file lower.c");
      if ((int)*(str + i) <= 'Z') {
        pathcrawler_trace_full("+118","l.4, file lower.c");
        lin_ite_body_7: *(str + i) = (char)((int)*(str + i) + 32);
      }
      else pathcrawler_trace_full("-118","l.4, file lower.c");
    }
    else pathcrawler_trace_full("-114","l.4, file lower.c");
    lin_for_action_3: i ++;
  }
  lin_for_break_1: ;
  return;
}


