/************TEST DRIVER FOR TEST CASE TC_9 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../merge.c"
#include "../../../pathcrawler_merge/lanceur_mergeSorted_params.h"
#undef main


int main()
{
//declarations
//allocations
arr1 = NULL;
arr2 = NULL;
result = NULL;
//assignments
size1 = 1695710423;
size2 = 0;
//function call
mergeSorted(arr1, size1, arr2, size2, result);
//disallocation
//end
}
