/************TEST DRIVER FOR TEST CASE TC_1 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../lower.c"
#include "../../../pathcrawler_lower/lanceur_toLowerCase_params.h"
#undef main


int main()
{
//declarations
//allocations
str = NULL;
//assignments
//function call
toLowerCase(str);
//disallocation
//end
}
