/************TEST DRIVER FOR TEST CASE TC_1 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../insert.c"
#include "../../../pathcrawler_insert/lanceur_insertAtHead_params.h"
#undef main


int main()
{
//declarations
//allocations
head = NULL;
//assignments
value = 0;
//function call
insertAtHead(head, value);
//disallocation
//end
}
