/************TEST DRIVER FOR TEST CASE TC_1 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../max.c"
#include "../../../pathcrawler_max/lanceur_findMax_params.h"
#undef main


int main()
{
//declarations
//allocations
arr = NULL;
//assignments
size = 0;
//function call
findMax(arr, size);
//disallocation
//end
}
