/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

struct Node {
   int data ;
   struct Node *next ;
};
extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

extern int ( /* missing proto */ malloc)(unsigned long x_0);

struct Node *insertAtHead(struct Node *head, int value)
{
  int __tmp_lin_0;
  __tmp_lin_0 = malloc(sizeof(struct Node));
  struct Node *newNode = (struct Node *)__tmp_lin_0;
  newNode->data = value;
  newNode->next = head;
  return newNode;
}


