/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

void mergeSorted(int *arr1, int size1, int *arr2, int size2, int *result)
{
  int __tmp_lin_7;
  int __tmp_lin_6;
  int __tmp_lin_5;
  int __tmp_lin_4;
  int __tmp_lin_3;
  int __tmp_lin_2;
  int __tmp_lin_1;
  int __tmp_lin_0;
  int i = 0;
  int j = 0;
  int k = 0;
  while (1) {
    if (i < size1) {
      pathcrawler_trace_full("+255","l.5, file merge.c");
      if (j < size2) {
        pathcrawler_trace_full("+259","l.5, file merge.c");
        goto lin_while_body_2;
      }
      else {
        pathcrawler_trace_full("-259","l.5, file merge.c");
        goto lin_while_break_1;
      }
    }
    else {
      pathcrawler_trace_full("-255","l.5, file merge.c");
      goto lin_while_break_1;
    }
    lin_while_body_2:
    if (*(arr1 + i) < *(arr2 + j)) {
      pathcrawler_trace_full("+265","l.6, file merge.c");
      lin_ite_body_9:
      {
        __tmp_lin_0 = k;
        k ++;
        __tmp_lin_1 = i;
        i ++;
        *(result + __tmp_lin_0) = *(arr1 + __tmp_lin_1);
      }
    }
    else {
      pathcrawler_trace_full("-265","l.6, file merge.c");
      lin_ite_body_10:
      {
        __tmp_lin_2 = k;
        k ++;
        __tmp_lin_3 = j;
        j ++;
        *(result + __tmp_lin_2) = *(arr2 + __tmp_lin_3);
      }
    }
  }
  lin_while_break_1: ;
  while (1) {
    if (i < size1) {
      pathcrawler_trace_full("+283","l.13, file merge.c");
      goto lin_while_body_14;
    }
    else {
      pathcrawler_trace_full("-283","l.13, file merge.c");
      goto lin_while_break_13;
    }
    lin_while_body_14:
    {
      __tmp_lin_4 = k;
      k ++;
      __tmp_lin_5 = i;
      i ++;
      *(result + __tmp_lin_4) = *(arr1 + __tmp_lin_5);
    }
  }
  lin_while_break_13: ;
  while (1) {
    if (j < size2) {
      pathcrawler_trace_full("+296","l.17, file merge.c");
      goto lin_while_body_18;
    }
    else {
      pathcrawler_trace_full("-296","l.17, file merge.c");
      goto lin_while_break_17;
    }
    lin_while_body_18:
    {
      __tmp_lin_6 = k;
      k ++;
      __tmp_lin_7 = j;
      j ++;
      *(result + __tmp_lin_6) = *(arr2 + __tmp_lin_7);
    }
  }
  lin_while_break_17: ;
  return;
}


