/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

struct Queue {
   int arr[100] ;
   int front ;
   int rear ;
   int size ;
};
extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

void enqueue(struct Queue *q, int value)
{
  q->rear = (q->rear + 1) % 100;
  q->arr[q->rear] = value;
  (q->size) ++;
  return;
}


