/************TEST DRIVER FOR TEST CASE TC_9 *************/
/* Generated by the PathCrawler test generation tool */
#include <stdio.h>
#include <stdlib.h>
#include"td_assume.h"
#define main pathcrawler___main
#include "../../../gcd.c"
#include "../../../pathcrawler_gcd/lanceur_gcd_params.h"
#undef main


int main()
{
//declarations
//allocations
//assignments
a = 152845094;
b = 878020551;
//function call
gcd(a, b);
//disallocation
//end
}
